import cafePhoto from "@/assets/place-cafe.jpg";
import foodPhoto from "@/assets/place-food.jpg";
import parkPhoto from "@/assets/place-park.jpg";
import transitPhoto from "@/assets/place-transit.jpg";
import type {
  CategoryMeta,
  Driver,
  Place,
  PlaceCollection,
  PlatformUser,
  Venue,
  VehicleCategory,
} from "@/types";

export const categoryMeta: CategoryMeta[] = [
  { id: "cafe", label: "Cafés", icon: "Coffee" },
  { id: "restaurant", label: "Restaurantes", icon: "UtensilsCrossed" },
  { id: "market", label: "Mercados", icon: "ShoppingBasket" },
  { id: "pharmacy", label: "Farmácias", icon: "Pill" },
  { id: "fuel", label: "Postos", icon: "Fuel" },
  { id: "health", label: "Saúde", icon: "HeartPulse" },
  { id: "hotel", label: "Hotéis", icon: "BedDouble" },
  { id: "shop", label: "Lojas", icon: "Tag" },
  { id: "park", label: "Parques", icon: "Trees" },
  { id: "transit", label: "Transporte", icon: "TrainFront" },
  { id: "culture", label: "Cultura", icon: "Landmark" },
];

export const vehicleCategories: VehicleCategory[] = [
  {
    id: "go",
    name: "Zuvvi Go",
    tagline: "Rápido e econômico",
    seats: 4,
    fareMultiplier: 1,
    etaMinutes: 3,
  },
  {
    id: "comfort",
    name: "Zuvvi Comfort",
    tagline: "Mais espaço e conforto",
    seats: 4,
    fareMultiplier: 1.45,
    etaMinutes: 5,
  },
  {
    id: "black",
    name: "Zuvvi Black",
    tagline: "Executivo premium",
    seats: 4,
    fareMultiplier: 2.1,
    etaMinutes: 8,
  },
];

export const demoUserLocation = { lat: 38.7169, lng: -9.1399 };

export const demoPlaces: Place[] = [
  {
    id: "zv-bistro-sapphire",
    name: "Bistrô Sapphire",
    category: "restaurant",
    subtitle: "Cozinha autoral · €€€",
    address: "Rua Garrett 42, Chiado",
    location: { lat: 38.7106, lng: -9.1417 },
    rating: 4.8,
    reviewCount: 2140,
    priceLevel: 3,
    openNow: true,
    hours: "Aberto até 23:30",
    weeklyHours: ["Seg – Qui · 12:00 – 23:30", "Sex – Sáb · 12:00 – 01:00", "Dom · 12:00 – 22:00"],
    phone: "+351 210 993 214",
    tags: ["Jantar", "Vinhos", "Terraço"],
    photos: [foodPhoto, cafePhoto],
    description: "Menu degustação sazonal em um salão de mármore escuro com vista para o Tejo.",
  },
  {
    id: "zv-emporio-central",
    name: "Empório Central",
    category: "market",
    subtitle: "Mercado gourmet",
    address: "Av. da Liberdade 118",
    location: { lat: 38.7223, lng: -9.1451 },
    rating: 4.6,
    reviewCount: 890,
    priceLevel: 2,
    openNow: true,
    hours: "Aberto até 22:00",
    weeklyHours: ["Seg – Sáb · 08:00 – 22:00", "Dom · 09:00 – 20:00"],
    phone: "+351 213 447 100",
    tags: ["Hortifruti", "Padaria", "Entrega"],
    photos: [cafePhoto],
    description: "Produtores locais, padaria artesanal e adega selecionada.",
  },
  {
    id: "zv-hospital-memorial",
    name: "Hospital Memorial",
    category: "health",
    subtitle: "Emergência 24h",
    address: "Rua Castilho 90",
    location: { lat: 38.7248, lng: -9.1533 },
    rating: 4.4,
    reviewCount: 1320,
    openNow: true,
    hours: "Aberto 24 horas",
    weeklyHours: ["Todos os dias · 24 horas"],
    phone: "+351 217 220 900",
    tags: ["Urgência", "Estacionamento", "Pediatria"],
    photos: [transitPhoto],
    description: "Centro hospitalar com urgência permanente e imagiologia.",
  },
  {
    id: "zv-posto-energy",
    name: "Posto Zuvvi Energy",
    category: "fuel",
    subtitle: "Combustível + carga elétrica",
    address: "Av. Almirante Reis 210",
    location: { lat: 38.7331, lng: -9.1349 },
    rating: 4.5,
    reviewCount: 460,
    priceLevel: 2,
    openNow: true,
    hours: "Aberto 24 horas",
    weeklyHours: ["Todos os dias · 24 horas"],
    phone: "+351 218 120 455",
    tags: ["Carregador rápido", "Loja", "Lavagem"],
    photos: [transitPhoto],
    description: "Oito carregadores DC de 150 kW e loja de conveniência aberta 24h.",
  },
  {
    id: "zv-drogaria-violet",
    name: "Drogaria Violet",
    category: "pharmacy",
    subtitle: "Farmácia de serviço",
    address: "Rua da Prata 63",
    location: { lat: 38.7108, lng: -9.1362 },
    rating: 4.7,
    reviewCount: 305,
    priceLevel: 2,
    openNow: false,
    hours: "Abre às 08:30",
    weeklyHours: ["Seg – Sáb · 08:30 – 20:00", "Dom · fechado"],
    phone: "+351 213 461 077",
    tags: ["Manipulação", "Vacinas", "Entrega"],
    photos: [cafePhoto],
    description: "Atendimento farmacêutico, testes rápidos e entrega no mesmo dia.",
  },
  {
    id: "zv-grand-hotel-royal",
    name: "Grand Hotel Royal",
    category: "hotel",
    subtitle: "5 estrelas · Rooftop",
    address: "Praça do Comércio 8",
    location: { lat: 38.7075, lng: -9.1364 },
    rating: 4.9,
    reviewCount: 3760,
    priceLevel: 4,
    openNow: true,
    hours: "Recepção 24 horas",
    weeklyHours: ["Check-in 15:00 · Check-out 12:00"],
    phone: "+351 210 400 800",
    tags: ["Spa", "Rooftop", "Vista rio"],
    photos: [foodPhoto, parkPhoto],
    description: "Suítes com vista para o Tejo, spa subterrâneo e bar panorâmico.",
  },
  {
    id: "zv-tech-store",
    name: "Tech Store Zuvvi",
    category: "shop",
    subtitle: "Eletrônicos e acessórios",
    address: "Rua Augusta 155",
    location: { lat: 38.7132, lng: -9.1385 },
    rating: 4.3,
    reviewCount: 712,
    priceLevel: 3,
    openNow: true,
    hours: "Aberto até 21:00",
    weeklyHours: ["Seg – Sáb · 10:00 – 21:00", "Dom · 11:00 – 19:00"],
    phone: "+351 213 240 660",
    tags: ["Assistência", "Retirada rápida"],
    photos: [transitPhoto],
    description: "Suporte técnico no mesmo dia e retirada em 30 minutos.",
  },
  {
    id: "zv-cafe-origem",
    name: "Café Origem",
    category: "cafe",
    subtitle: "Torra própria",
    address: "Rua do Alecrim 21",
    location: { lat: 38.7091, lng: -9.1445 },
    rating: 4.8,
    reviewCount: 1180,
    priceLevel: 2,
    openNow: true,
    hours: "Aberto até 19:00",
    weeklyHours: ["Seg – Dom · 07:30 – 19:00"],
    phone: "+351 213 471 900",
    tags: ["Especialidade", "Wi-Fi", "Vegano"],
    photos: [cafePhoto],
    description: "Micro-lotes torrados no local e fermentações experimentais.",
  },
  {
    id: "zv-parque-eduardo",
    name: "Parque Miradouro",
    category: "park",
    subtitle: "Mirante e jardins",
    address: "Alto do Parque",
    location: { lat: 38.7283, lng: -9.1509 },
    rating: 4.7,
    reviewCount: 5400,
    openNow: true,
    hours: "Aberto até 22:00",
    weeklyHours: ["Todos os dias · 06:00 – 22:00"],
    tags: ["Corrida", "Vista", "Pet friendly"],
    photos: [parkPhoto],
    description: "Terraços ajardinados com a melhor vista noturna da cidade.",
  },
  {
    id: "zv-estacao-central",
    name: "Estação Central",
    category: "transit",
    subtitle: "Metro + trem regional",
    address: "Praça Central",
    location: { lat: 38.7201, lng: -9.1301 },
    rating: 4.2,
    reviewCount: 2260,
    openNow: true,
    hours: "05:30 – 01:00",
    weeklyHours: ["Todos os dias · 05:30 – 01:00"],
    tags: ["Metro", "Trem", "Acessível"],
    photos: [transitPhoto],
    description: "Interface de quatro linhas com bicicletários e Zuvvi point.",
  },
  {
    id: "zv-museu-luz",
    name: "Museu da Luz",
    category: "culture",
    subtitle: "Arte contemporânea",
    address: "Doca de Santo Amaro",
    location: { lat: 38.7043, lng: -9.1721 },
    rating: 4.6,
    reviewCount: 1490,
    priceLevel: 2,
    openNow: true,
    hours: "Aberto até 20:00",
    weeklyHours: ["Ter – Dom · 10:00 – 20:00", "Seg · fechado"],
    phone: "+351 213 612 800",
    tags: ["Exposições", "Loja", "Café"],
    photos: [parkPhoto],
    description: "Instalações de luz e som em antigos armazéns portuários.",
  },
];

export const demoCollections: PlaceCollection[] = [
  {
    id: "col-noite",
    title: "Noite premium",
    description: "Jantar, rooftop e vista para o rio",
    placeIds: ["zv-bistro-sapphire", "zv-grand-hotel-royal", "zv-museu-luz"],
  },
  {
    id: "col-essenciais",
    title: "Essenciais do dia",
    description: "Mercado, farmácia e café perto de você",
    placeIds: ["zv-emporio-central", "zv-drogaria-violet", "zv-cafe-origem"],
  },
  {
    id: "col-mobilidade",
    title: "Mobilidade",
    description: "Recarga, transporte e apoio 24h",
    placeIds: ["zv-posto-energy", "zv-estacao-central", "zv-hospital-memorial"],
  },
];

export const demoDrivers: Driver[] = [
  {
    id: "drv-01",
    name: "Marina Alves",
    status: "online",
    currentLocation: { lat: 38.7188, lng: -9.1428 },
    heading: 45,
    speed: 32,
    vehicle: { model: "Tesla Model 3", plate: "ZV-14-QA", color: "Grafite", category: "black" },
    currentTripId: null,
    rating: 4.94,
    avatar: "MA",
    tripsToday: 11,
  },
  {
    id: "drv-02",
    name: "Rui Bettencourt",
    status: "on_trip",
    currentLocation: { lat: 38.7132, lng: -9.1372 },
    heading: 190,
    speed: 24,
    vehicle: { model: "Toyota Corolla", plate: "ZV-08-BR", color: "Prata", category: "comfort" },
    currentTripId: "trp-1001",
    rating: 4.88,
    avatar: "RB",
    tripsToday: 9,
  },
  {
    id: "drv-03",
    name: "Sofia Lima",
    status: "online",
    currentLocation: { lat: 38.7248, lng: -9.1372 },
    heading: 300,
    speed: 41,
    vehicle: { model: "Renault Zoe", plate: "ZV-52-LM", color: "Azul", category: "go" },
    currentTripId: null,
    rating: 4.91,
    avatar: "SL",
    tripsToday: 14,
  },
  {
    id: "drv-04",
    name: "Tiago Nunes",
    status: "online",
    currentLocation: { lat: 38.7091, lng: -9.1481 },
    heading: 120,
    speed: 18,
    vehicle: { model: "Mercedes EQE", plate: "ZV-77-TN", color: "Preto", category: "black" },
    currentTripId: null,
    rating: 4.97,
    avatar: "TN",
    tripsToday: 6,
  },
  {
    id: "drv-05",
    name: "Cláudia Reis",
    status: "on_trip",
    currentLocation: { lat: 38.7305, lng: -9.1442 },
    heading: 15,
    speed: 36,
    vehicle: { model: "Peugeot 508", plate: "ZV-31-CR", color: "Branco", category: "comfort" },
    currentTripId: "trp-1002",
    rating: 4.82,
    avatar: "CR",
    tripsToday: 12,
  },
  {
    id: "drv-06",
    name: "Hugo Ferreira",
    status: "offline",
    currentLocation: { lat: 38.7062, lng: -9.1622 },
    heading: 270,
    speed: 0,
    vehicle: { model: "Nissan Leaf", plate: "ZV-19-HF", color: "Cinza", category: "go" },
    currentTripId: null,
    rating: 4.75,
    avatar: "HF",
    tripsToday: 0,
  },
];

export const demoPlatformUsers: PlatformUser[] = [
  {
    id: "usr-01",
    name: "Ana Duarte",
    email: "ana.duarte@zuvvi.app",
    role: "user",
    city: "Lisboa",
    trips: 84,
    joinedAt: "2024-03-12",
  },
  {
    id: "usr-02",
    name: "Marina Alves",
    email: "marina.alves@zuvvi.app",
    role: "driver",
    city: "Lisboa",
    trips: 1_842,
    joinedAt: "2023-08-02",
  },
  {
    id: "usr-03",
    name: "Paulo Serra",
    email: "paulo@emporiocentral.pt",
    role: "business_owner",
    city: "Lisboa",
    trips: 12,
    joinedAt: "2024-11-19",
  },
  {
    id: "usr-04",
    name: "Zuvvi Ops",
    email: "ops@zuvvi.app",
    role: "admin",
    city: "Lisboa",
    trips: 0,
    joinedAt: "2023-01-04",
  },
  {
    id: "usr-05",
    name: "Beatriz Rocha",
    email: "beatriz.rocha@zuvvi.app",
    role: "user",
    city: "Cascais",
    trips: 47,
    joinedAt: "2025-02-08",
  },
];

export const demoVenues: Venue[] = [
  {
    id: "ven-01",
    name: "Bistrô Sapphire",
    owner: "Grupo Sapphire",
    category: "Restaurante",
    address: "Rua Garrett 42",
    location: { lat: 38.7106, lng: -9.1417 },
    rating: 4.8,
    status: "active",
  },
  {
    id: "ven-02",
    name: "Empório Central",
    owner: "Paulo Serra",
    category: "Mercado",
    address: "Av. da Liberdade 118",
    location: { lat: 38.7223, lng: -9.1451 },
    rating: 4.6,
    status: "active",
  },
  {
    id: "ven-03",
    name: "Tech Store Zuvvi",
    owner: "Zuvvi Retail",
    category: "Loja",
    address: "Rua Augusta 155",
    location: { lat: 38.7132, lng: -9.1385 },
    rating: 4.3,
    status: "review",
  },
  {
    id: "ven-04",
    name: "Drogaria Violet",
    owner: "Violet Saúde",
    category: "Farmácia",
    address: "Rua da Prata 63",
    location: { lat: 38.7108, lng: -9.1362 },
    rating: 4.7,
    status: "paused",
  },
];

export const demoStreetNames = [
  "Av. da Liberdade",
  "Rua Augusta",
  "Av. Almirante Reis",
  "Rua Castilho",
  "Av. 24 de Julho",
  "Rua da Prata",
  "Av. Principal",
];
